
package Vista.Admin;

import Vista.Usuario.VentanaRegistro;
import Modelo.ConexionSingleton.MantenerSession;
import Vista.Admin.enviarNotificacion;
import Vista.Admin.tablaRegistros;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class VentanaAdmin extends javax.swing.JFrame {

    //ahora
    private enviarNotificacion ventanaNotificacion;
    private tablaRegistros panelTablaRegistros;
   
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaAdmin() {
        initComponents();
         
        updateUserInfo();
        // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);  // Esto coloca la ventana en el centro
        btnRegistro.setEnabled(false);
        
  
    }
    
     // Método para actualizar la información del usuario
    public void updateUserInfo() {
        MantenerSession sessionManager = MantenerSession.getInstance();
        if (sessionManager.isUserLoggedIn()) {
            String nombre = sessionManager.getNombre();
            String correo = sessionManager.getCorreo();
            String rol = sessionManager.getRol();

            // Actualiza los labels
            lblUsuario.setText("Usuario: " + nombre);
            lblCorreo.setText("Correo: " + correo);
            lblRol.setText("Rol: " + rol);
        }
    }
     

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelCambiable = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnNotificaciones = new javax.swing.JButton();
        btnEstadistica = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        btnTablaRegistro = new javax.swing.JButton();
        btnNotificar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 60));
        setSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(165, 214, 167));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion Responsable de Residuos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 785, 118));

        panelCambiable.setBackground(new java.awt.Color(0, 255, 204));
        panelCambiable.setMaximumSize(new java.awt.Dimension(700, 400));
        panelCambiable.setMinimumSize(new java.awt.Dimension(700, 400));

        javax.swing.GroupLayout panelCambiableLayout = new javax.swing.GroupLayout(panelCambiable);
        panelCambiable.setLayout(panelCambiableLayout);
        panelCambiableLayout.setHorizontalGroup(
            panelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelCambiableLayout.setVerticalGroup(
            panelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel1.add(panelCambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 120, 30));

        btnServicios.setBackground(new java.awt.Color(102, 153, 255));
        btnServicios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnServicios.setText("Servicios");
        jPanel1.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, 30));

        btnNotificaciones.setBackground(new java.awt.Color(102, 153, 255));
        btnNotificaciones.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnNotificaciones.setText("Notificaciones");
        btnNotificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificacionesActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotificaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 130, 30));

        btnEstadistica.setBackground(new java.awt.Color(102, 153, 255));
        btnEstadistica.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEstadistica.setText("Estadísticas");
        jPanel1.add(btnEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 120, 30));

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 30));

        lblRol.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 30));

        btnTablaRegistro.setBackground(new java.awt.Color(165, 214, 167));
        btnTablaRegistro.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnTablaRegistro.setForeground(new java.awt.Color(255, 51, 51));
        btnTablaRegistro.setText("Tabla De Registros");
        btnTablaRegistro.setBorder(null);
        btnTablaRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTablaRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnTablaRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 180, 50));

        btnNotificar.setBackground(new java.awt.Color(165, 214, 167));
        btnNotificar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        btnNotificar.setForeground(new java.awt.Color(51, 51, 255));
        btnNotificar.setText("Notificar");
        btnNotificar.setBorder(null);
        btnNotificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNotificarActionPerformed(evt);
            }
        });
        jPanel1.add(btnNotificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 80, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //metodo para Registros pero esta off porque estoy como admin
    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
    // Crear una nueva instancia del panel de registro
    VentanaRegistro ventanaRegistro = new VentanaRegistro();
    
    // Limpiar el panel actual (opcional, si deseas borrar el contenido del panel antes de agregar el nuevo)
    panelCambiable.removeAll();  // Elimina todos los componentes dentro de panelCambiable
    
    // Agregar el nuevo panel de registro al panelCambiable
    panelCambiable.add(ventanaRegistro);  // Añadir el panel de registro
    
    // Actualizar la vista para reflejar el cambio de panel
    panelCambiable.revalidate();   // Revalidar para actualizar el diseño
    panelCambiable.repaint();      // Volver a pintar el panel para reflejar el cambio
    
    // Ajustar el tamaño del panel de registro al tamaño disponible en el contenedor
    ventanaRegistro.setSize(panelCambiable.getSize());  // Ajusta el tamaño del nuevo panel
    
    // Cambiar al Tab 2 (índice 1) cuando se muestra la VentanaRegistro
    ventanaRegistro.getTabbedPane().setSelectedIndex(1); // Cambiar al Tab 2 (Clasificación de Residuo)
    
    // Establecer el foco en el primer campo de texto del tab 2
    ventanaRegistro.getTxtNombreClaResiduo().requestFocusInWindow();  // Establecer el foco en el primer campo
    }//GEN-LAST:event_btnRegistroActionPerformed

    //por ahora no se usa esto
    private void btnNotificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificacionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNotificacionesActionPerformed

    //metodo para que se superponga el Jpanel tablaRegistros en panelCambiable
    private void btnTablaRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTablaRegistroActionPerformed
         /**
        tablaRegistros tablaRegistros = new tablaRegistros(); // Asegúrate de tener esta clase creada

        // Limpiar el panel actual (opcional, si deseas borrar el contenido del panel antes de agregar el nuevo)
        panelCambiable.removeAll();  // Elimina todos los componentes dentro de panelCambiable

        // Agregar el nuevo panel de registros al panelCambiable
        panelCambiable.add(tablaRegistros);  // Añadir el panel de registros

        // Actualizar la vista para reflejar el cambio de panel
        panelCambiable.revalidate();   // Revalidar para actualizar el diseño
        panelCambiable.repaint();      // Volver a pintar el panel para reflejar el cambio

        // Ajustar el tamaño del panel de registros al tamaño disponible en el contenedor
        tablaRegistros.setSize(panelCambiable.getSize());  // Ajusta el tamaño del nuevo panel
        
         */
        
        //nuevo
        // Crear una nueva instancia del panel de registros
        tablaRegistros panelTabla = new tablaRegistros(); 

        // Limpiar el panel actual
        panelCambiable.removeAll();  

        // Crear una nueva instancia de la ventana de notificación
        ventanaNotificacion = new enviarNotificacion();

        // Pasar la referencia de la ventana de notificación a tablaRegistros
        panelTabla.setVentanaNotificacion(ventanaNotificacion); 

        // Agregar el nuevo panel de registros al panelCambiable
        panelCambiable.add(panelTabla);  

        // Actualizar la vista para reflejar el cambio de panel
        panelCambiable.revalidate();   
        panelCambiable.repaint();      

        // Ajustar el tamaño del panel de registros al tamaño disponible en el contenedor
        panelTabla.setSize(panelCambiable.getSize());  
        
    }//GEN-LAST:event_btnTablaRegistroActionPerformed

    private void btnNotificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNotificarActionPerformed
        //accion para notificar y se habra el Jframe enviarNotificacion
        // Primero, verifica si ya se ha seleccionado un DNI en la tabla (esto se hace en tablaRegistros)
    if (ventanaNotificacion != null) {
        // Si ya se ha seleccionado un DNI y la ventana de notificación está disponible:
        
        // Abre la ventana de notificación
        ventanaNotificacion.setVisible(true);  
        
        // El DNI ya fue establecido en la tablaRegistros, se usa en el campo txtIdUsuario de la ventanaNotificacion
    } else {
        // Si no se ha seleccionado ningún DNI, muestra un mensaje al usuario
        JOptionPane.showMessageDialog(this, "¡Por favor, selecciona un usuario de la tabla primero!", "Advertencia", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnNotificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnNotificaciones;
    private javax.swing.JToggleButton btnNotificar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnTablaRegistro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelCambiable;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnEstadistica() {
        return btnEstadistica;
    }

    public void setBtnEstadistica(JButton btnEstadistica) {
        this.btnEstadistica = btnEstadistica;
    }

    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public void setBtnRegistro(JButton btnRegistro) {
        this.btnRegistro = btnRegistro;
    }

    public JButton getBtnServicios() {
        return btnServicios;
    }

    public void setBtnServicios(JButton btnServicios) {
        this.btnServicios = btnServicios;
    }

    public JButton getBtnSugerencias() {
        return btnNotificaciones;
    }

    public void setBtnSugerencias(JButton btnSugerencias) {
        this.btnNotificaciones = btnSugerencias;
    }

    


}

