/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Usuario;

import Modelo.ConexionSingleton.MantenerSession;
import Vista.Login;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author sankef
 */
public class VentanaUsuario extends javax.swing.JFrame {

        // Declarar como atributo para reutilizar la instancia si es necesario
        private VentanaRegistro ventanaRegistroPanel; 
        
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaUsuario() {
        initComponents();
         
        //reutilizar el usuario guardado ( codigo guardado)
        updateUserInfo();
        // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);  
    }
    
     // Método para actualizar la información del usuario
    public void updateUserInfo() {
        MantenerSession sessionManager = MantenerSession.getInstance();
        if (sessionManager.isUserLoggedIn()) {
            String nombre = sessionManager.getNombre();
            String correo = sessionManager.getCorreo();
            String rol = sessionManager.getRol();

            // Actualiza los labels
            lblUsuario.setText("Usuario: " + nombre);
            lblCorreo.setText("Correo: " + correo);
            lblRol.setText("Rol: " + rol);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Salir = new javax.swing.JLabel();
        panelCambiable = new javax.swing.JPanel();
        btnRegistro = new javax.swing.JButton();
        btnServicios = new javax.swing.JButton();
        btnSugerencias = new javax.swing.JButton();
        btnEstadistica = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        btnDeslogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1080, 60));
        setSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(165, 214, 167));
        jPanel1.setMaximumSize(new java.awt.Dimension(1080, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(1080, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Salir.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setText("Gestion Responsable de Residuos");
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 760, 100));

        panelCambiable.setMaximumSize(new java.awt.Dimension(700, 400));
        panelCambiable.setMinimumSize(new java.awt.Dimension(700, 400));

        javax.swing.GroupLayout panelCambiableLayout = new javax.swing.GroupLayout(panelCambiable);
        panelCambiable.setLayout(panelCambiableLayout);
        panelCambiableLayout.setHorizontalGroup(
            panelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        panelCambiableLayout.setVerticalGroup(
            panelCambiableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        jPanel1.add(panelCambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, -1, -1));

        btnRegistro.setBackground(new java.awt.Color(255, 255, 51));
        btnRegistro.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRegistro.setText("Registro");
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 120, 30));

        btnServicios.setBackground(new java.awt.Color(102, 153, 255));
        btnServicios.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnServicios.setText("Servicios");
        jPanel1.add(btnServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 120, 30));

        btnSugerencias.setBackground(new java.awt.Color(102, 153, 255));
        btnSugerencias.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSugerencias.setText("Sugerencias");
        btnSugerencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSugerenciasActionPerformed(evt);
            }
        });
        jPanel1.add(btnSugerencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 120, 30));

        btnEstadistica.setBackground(new java.awt.Color(102, 153, 255));
        btnEstadistica.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnEstadistica.setText("Estadísticas");
        btnEstadistica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticaActionPerformed(evt);
            }
        });
        jPanel1.add(btnEstadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 120, 30));

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 270, 30));

        lblRol.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jPanel1.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 270, 30));

        btnDeslogin.setText("Deslogear");
        btnDeslogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesloginActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeslogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 10, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
    // Mostrar una ventana de confirmación antes de proceder con el registro
    int respuesta = JOptionPane.showConfirmDialog(this, 
        "¿Deseas registrar un residuo?", 
        "Confirmación", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

    // Si el usuario selecciona "Sí" (JOptionPane.YES_OPTION)
    if (respuesta == JOptionPane.YES_OPTION) {
        // Crear una nueva instancia del panel de registro
        VentanaRegistro ventanaRegistro = new VentanaRegistro();
        
        // Limpiar el panel actual (opcional, si deseas borrar el contenido del panel antes de agregar el nuevo)
        panelCambiable.removeAll();  // Elimina todos los componentes dentro de panelCambiable
        
        // Agregar el nuevo panel de registro al panelCambiable
        panelCambiable.add(ventanaRegistro);  // Añadir el panel de registro
        
        // Actualizar la vista para reflejar el cambio de panel
        panelCambiable.revalidate();   // Revalidar para actualizar el diseño
        panelCambiable.repaint();      // Volver a pintar el panel para reflejar el cambio
        
        // Ajustar el tamaño del panel de registro al tamaño disponible en el contenedor
        ventanaRegistro.setSize(panelCambiable.getSize());  // Ajusta el tamaño del nuevo panel
        
        // Cambiar al Tab 1 (índice 1) cuando se muestra la VentanaRegistro
        ventanaRegistro.getTabbedPane().setSelectedIndex(1); // Cambiar al Tab 1 (Registro de Residuo)
        
        // Bloquear el Tab 2 (índice 2) para que no pueda ser seleccionado
        ventanaRegistro.getTabbedPane().setEnabledAt(2, false); // Desactivar Tab 2
        
        // Establecer el foco en el primer campo de texto del tab 1 (puedes ajustarlo según lo que necesitas)
        ventanaRegistro.getTxtNombreClaResiduo().requestFocusInWindow();  // Establecer el foco en el primer campo
    } else {
        // Si el usuario selecciona "No" o cierra la ventana, no hacer nada
        JOptionPane.showMessageDialog(this, 
            "Operación cancelada. No se registró el residuo.", 
            "Cancelado", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnSugerenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSugerenciasActionPerformed
    // Mostrar una ventana de confirmación antes de proceder con el registro de mensajes
    int respuesta = JOptionPane.showConfirmDialog(this, 
        "¿Deseas ver los mensajes de notificación?", 
        "Confirmación", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

    // Si el usuario selecciona "Sí" (JOptionPane.YES_OPTION)
    if (respuesta == JOptionPane.YES_OPTION) {
        // Crear una nueva instancia del panel de mensajes (VentanaMensajes)
        VentanaMensajes ventanaMensajes = new VentanaMensajes();
        
        // Limpiar el panel actual (opcional, si deseas borrar el contenido del panel antes de agregar el nuevo)
        panelCambiable.removeAll();  // Elimina todos los componentes dentro de panelCambiable
        
        // Agregar el nuevo panel de mensajes al panelCambiable
        panelCambiable.add(ventanaMensajes);  // Añadir el panel de mensajes
        
        // Actualizar la vista para reflejar el cambio de panel
        panelCambiable.revalidate();   // Revalidar para actualizar el diseño
        panelCambiable.repaint();      // Volver a pintar el panel para reflejar el cambio
        
        // Ajustar el tamaño del panel de mensajes al tamaño disponible en el contenedor
        ventanaMensajes.setSize(panelCambiable.getSize());  // Ajusta el tamaño del nuevo panel
        
        // Cambiar al Tab correspondiente (tab de Correo) al abrir la ventana
        ventanaMensajes.getTabGeneral().setSelectedIndex(0); // Cambiar al Tab 0 (Correo)

        // Cargar los mensajes de Correo directamente al abrir el panel
        ventanaMensajes.cargarMensajesCorreo(ventanaMensajes.getTablaCorreo());  // Llamamos a la función que carga los mensajes

        // Si deseas bloquear un tab específico, lo puedes hacer como en el caso anterior
        // ventanaMensajes.getTabGeneral().setEnabledAt(1, false); // Ejemplo para bloquear otro tab si es necesario

    } else {
        // Si el usuario selecciona "No" o cierra la ventana, no hacer nada
        JOptionPane.showMessageDialog(this, 
            "Operación cancelada. No se mostraron los mensajes.", 
            "Cancelado", 
            JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnSugerenciasActionPerformed

    private void btnDesloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesloginActionPerformed
        // Llamamos al método logout de la clase MantenerSession para cerrar la sesión
        MantenerSession.getInstance().logout();

        // Mostrar mensaje de confirmación
        JOptionPane.showMessageDialog(this, "Sesión cerrada correctamente.", "Sesión cerrada", JOptionPane.INFORMATION_MESSAGE);

        // Redirigir a la ventana de login
        Login loginWindow = new Login();  // Crear una nueva instancia de la ventana de login
        loginWindow.setVisible(true);     // Hacerla visible

        // Cerrar la ventana de administración o la actual
        this.dispose();  // Cerrar la ventana actual (puede ser VentanaAdmin o la que sea)
    }//GEN-LAST:event_btnDesloginActionPerformed

    private void btnEstadisticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticaActionPerformed
        // Mostrar una ventana de confirmación antes de proceder con la apertura de la ventana de estadísticas
         int respuesta = JOptionPane.showConfirmDialog(this, 
             "¿Deseas ver las estadísticas?", 
             "Confirmación", 
             JOptionPane.YES_NO_OPTION, 
             JOptionPane.QUESTION_MESSAGE);

         // Si el usuario selecciona "Sí" (JOptionPane.YES_OPTION)
         if (respuesta == JOptionPane.YES_OPTION) {
             // Crear una nueva instancia del panel de estadísticas (VentanaEstadistica)
             VentanaEstadistica ventanaEstadistica = new VentanaEstadistica();

             // Limpiar el panel actual (opcional, si deseas borrar el contenido del panel antes de agregar el nuevo)
             panelCambiable.removeAll();  // Elimina todos los componentes dentro de panelCambiable

             // Agregar el nuevo panel de estadísticas al panelCambiable
             panelCambiable.add(ventanaEstadistica);  // Añadir el panel de estadísticas

             // Actualizar la vista para reflejar el cambio de panel
             panelCambiable.revalidate();   // Revalidar para actualizar el diseño
             panelCambiable.repaint();      // Volver a pintar el panel para reflejar el cambio

             // Ajustar el tamaño del panel de estadísticas al tamaño disponible en el contenedor
             ventanaEstadistica.setSize(panelCambiable.getSize());  // Ajusta el tamaño del nuevo panel

             // Si deseas cambiar de Tab en la vista de estadísticas, puedes hacerlo así:
             // ventanaEstadistica.getTabGeneral().setSelectedIndex(0); // Cambiar al Tab 0 si es necesario
         } else {
             // Si el usuario selecciona "No" o cierra la ventana, no hacer nada
             JOptionPane.showMessageDialog(this, 
                 "Operación cancelada. No se mostraron las estadísticas.", 
                 "Cancelado", 
                 JOptionPane.INFORMATION_MESSAGE);
         }
    }//GEN-LAST:event_btnEstadisticaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Salir;
    private javax.swing.JButton btnDeslogin;
    private javax.swing.JButton btnEstadistica;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnServicios;
    private javax.swing.JButton btnSugerencias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelCambiable;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnEstadistica() {
        return btnEstadistica;
    }

    public void setBtnEstadistica(JButton btnEstadistica) {
        this.btnEstadistica = btnEstadistica;
    }

    public JButton getBtnRegistro() {
        return btnRegistro;
    }

    public void setBtnRegistro(JButton btnRegistro) {
        this.btnRegistro = btnRegistro;
    }

    public JButton getBtnServicios() {
        return btnServicios;
    }

    public void setBtnServicios(JButton btnServicios) {
        this.btnServicios = btnServicios;
    }

    public JButton getBtnSugerencias() {
        return btnSugerencias;
    }

    public void setBtnSugerencias(JButton btnSugerencias) {
        this.btnSugerencias = btnSugerencias;
    }

    public VentanaRegistro getVentanaRegistroPanel() {
        return ventanaRegistroPanel;
    }

    public void setVentanaRegistroPanel(VentanaRegistro ventanaRegistroPanel) {
        this.ventanaRegistroPanel = ventanaRegistroPanel;
    }

    public JLabel getSalir() {
        return Salir;
    }

    public void setSalir(JLabel Salir) {
        this.Salir = Salir;
    }

    public JButton getBtnDeslogin() {
        return btnDeslogin;
    }

    public void setBtnDeslogin(JButton btnDeslogin) {
        this.btnDeslogin = btnDeslogin;
    }

    public JPanel getjPanel1() {
        return jPanel1;
    }

    public void setjPanel1(JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    public JLabel getLblCorreo() {
        return lblCorreo;
    }

    public void setLblCorreo(JLabel lblCorreo) {
        this.lblCorreo = lblCorreo;
    }

    public JLabel getLblRol() {
        return lblRol;
    }

    public void setLblRol(JLabel lblRol) {
        this.lblRol = lblRol;
    }

    public JLabel getLblUsuario() {
        return lblUsuario;
    }

    public void setLblUsuario(JLabel lblUsuario) {
        this.lblUsuario = lblUsuario;
    }

    public JPanel getPanelCambiable() {
        return panelCambiable;
    }

    public void setPanelCambiable(JPanel panelCambiable) {
        this.panelCambiable = panelCambiable;
    }

    

    

}

