/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import javax.swing.JOptionPane;
import Modelo.ConexionSingleton.MantenerSession;
import Modelo.Observer.BotonObservador;
import Modelo.Observer.Formulario;
import Modelo.Proxy.UsuarioProxy;
import Vista.Usuario.Registrarse;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
public class Login extends javax.swing.JFrame {
  
    //creacion del formulario para el patron Observer
    private Formulario formulario;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // Inicializamos el formulario (sujeto)
        formulario = new Formulario();
         // Inicializamos el botón observador
        BotonObservador botonObservador = new BotonObservador(this.btnIngresar); // Usamos btnIngresar

        // Registramos el observador en el formulario
        formulario.agregarObservador(botonObservador);
        
        // Centrar la ventana en la pantalla
        setLocationRelativeTo(null);  // Esto coloca la ventana en el centro
        camposPaso1();
    }

    
    //metodo para validar los campos llenos
    public void camposPaso1(){
    // Agregar el listener solo a los campos de correo y contraseña
    txtCorreo.addCaretListener(e -> actualizarEstadoFormulario());
    txtContrasena.addCaretListener(e -> actualizarEstadoFormulario());
    }
    
    // Actualizar el estado del formulario uso del patron Observer
    public void actualizarEstadoFormulario() {
        // Verifica que los campos de correo y contraseña estén llenos
        boolean formularioCompleto = !txtCorreo.getText().isEmpty() &&
                                      !new String(txtContrasena.getPassword()).isEmpty(); // Verifica que la contraseña no esté vacía

        // Habilita o deshabilita el botón "Ingresar" según el estado del formulario
        btnIngresar.setEnabled(formularioCompleto);
    }
    
    //validar que el correo sega @gmail.com.
    private boolean esCorreoValido(String correo) {
    // Expresión regular para validar el correo electrónico
    String regex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
    
    // Utiliza la expresión regular para validar el correo
    Pattern pattern = Pattern.compile(regex);
    Matcher matcher = pattern.matcher(correo);
    
    return matcher.matches();  // Retorna verdadero si el correo es válido
}
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblContraseña = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1080, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(165, 214, 167));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Acceso");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 62, 785, 118));

        jPanel2.setBackground(new java.awt.Color(165, 214, 167));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblContraseña.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblContraseña.setText("Contraseña");

        lblCorreo.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lblCorreo.setText("Correo");

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 204));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnIngresar.setBackground(new java.awt.Color(204, 255, 204));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCorreo)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(lblContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(54, 54, 54)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Gestion Responsable de Residuos");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 16, 785, 118));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
      // Crear la instancia del JFrame "Registrarse"
        Registrarse ventanaRegistro = new Registrarse();
        
        // Mostrar la ventana de registro
        ventanaRegistro.setVisible(true);
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        // Obtener los valores de los campos de texto
    String correo = txtCorreo.getText();
    String contrasena = new String(txtContrasena.getPassword()); // Suponiendo que txtContrasena es un JPasswordField

    // Validación del correo electrónico usando una expresión regular
    if (!esCorreoValido(correo)) {
        JOptionPane.showMessageDialog(this, "Correo electrónico no válido. Por favor ingresa un correo válido.", "Error de Login", JOptionPane.ERROR_MESSAGE);
        return;  // Salir de la función si el correo no es válido
    }

    // Autenticar al usuario
    MantenerSession sessionManager = MantenerSession.getInstance();
    if (sessionManager.autenticarUsuario(correo, contrasena)) {
        // Si la autenticación es exitosa, mostrar el mensaje de bienvenida y abrir el JFrame correspondiente
        JOptionPane.showMessageDialog(this, "Bienvenido " + sessionManager.getNombre()+" Rol:"+sessionManager.getRol(), "Login Exitoso", JOptionPane.INFORMATION_MESSAGE);
        
        // Llamar al proxy para abrir el JFrame según el rol
        String rol = sessionManager.getRol(); // Obtener el rol del usuario (Usuario o Admin)
        UsuarioProxy usuarioProxy = new UsuarioProxy();
        usuarioProxy.abrirJFrameSegunRol(rol); // Abre el JFrame correspondiente según el rol

        // Cerrar la ventana de login (opcional)
        this.dispose();
    } else {
        // Si la autenticación falla, mostrar un mensaje de error
        JOptionPane.showMessageDialog(this, "Credenciales incorrectas", "Error de Login", JOptionPane.ERROR_MESSAGE);
    }
   
    }//GEN-LAST:event_btnIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
