/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tester;

import Modelo.ConexionSingleton.MantenerSession;
import Modelo.Observer.BotonObservador;
import Modelo.Observer.Formulario;
import Vista.VentanaRegistro;
import java.awt.FlowLayout;

/**
 *
 * @author sankef
 */
public class ventanaMainUsuario extends javax.swing.JFrame {

    private VentanaRegistro ventanaRegistroPanel; // Declarar como atributo para reutilizar la instancia si es necesario

    public ventanaMainUsuario() {
        initComponents();
        
        updateUserInfo();
        
        
    }

    // Método para actualizar la información del usuario
    public void updateUserInfo() {
        MantenerSession sessionManager = MantenerSession.getInstance();
        if (sessionManager.isUserLoggedIn()) {
            String nombre = sessionManager.getNombre();
            String correo = sessionManager.getCorreo();
            String rol = sessionManager.getRol();

            // Actualiza los labels
            lblUsuario.setText("Usuario: " + nombre);
            lblCorreo.setText("Correo: " + correo);
            lblRol.setText("Rol: " + rol);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoColor = new javax.swing.JPanel();
        panelCambiable = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoColor.setBackground(new java.awt.Color(204, 255, 204));
        fondoColor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelCambiable.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        fondoColor.add(panelCambiable, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 700, 400));

        lblUsuario.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fondoColor.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 30));

        lblCorreo.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblCorreo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fondoColor.add(lblCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 200, 30));

        lblRol.setFont(new java.awt.Font("Roboto", 1, 15)); // NOI18N
        lblRol.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        fondoColor.add(lblRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 200, 30));

        jButton1.setBackground(new java.awt.Color(51, 255, 255));
        jButton1.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jButton1.setText("jButton1");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fondoColor.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 130, 40));

        jButton2.setBackground(new java.awt.Color(255, 255, 153));
        jButton2.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jButton2.setText("Registro");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        fondoColor.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, 130, 40));

        jButton3.setBackground(new java.awt.Color(51, 255, 255));
        jButton3.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jButton3.setText("Servicios");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fondoColor.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, 130, 40));

        jButton4.setBackground(new java.awt.Color(51, 255, 255));
        jButton4.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jButton4.setText("jButton1");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fondoColor.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 130, 40));

        getContentPane().add(fondoColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       // Crear una nueva instancia del panel de registro
    VentanaRegistro ventanaRegistro = new VentanaRegistro();
    
    // Limpiar el panel actual (opcional, si deseas borrar el contenido del panel antes de agregar el nuevo)
    panelCambiable.removeAll();  // Elimina todos los componentes dentro de panelCambiable
    
    // Agregar el nuevo panel de registro al panelCambiable
    panelCambiable.add(ventanaRegistro);  // Añadir el panel de registro
    
    // Actualizar la vista para reflejar el cambio de panel
    panelCambiable.revalidate();   // Revalidar para actualizar el diseño
    panelCambiable.repaint();      // Volver a pintar el panel para reflejar el cambio
    
    // Si deseas que el panel de registro ocupe todo el espacio disponible, puedes usar:
    ventanaRegistro.setSize(panelCambiable.getSize());  // Ajusta el tamaño del nuevo panel

    // Cambiar al Tab 2 (indice 1)
    ventanaRegistro.getTabbedPane().setSelectedIndex(1); // Cambiar al Tab 2 cuando se muestra la VentanaRegistro
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanaMainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanaMainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanaMainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanaMainUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaMainUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel fondoColor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblRol;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelCambiable;
    // End of variables declaration//GEN-END:variables


}
